// ─── Grading Companies ───

export type Grader = 'PSA' | 'BGS' | 'CGC' | 'SGC';
export const DEFAULT_GRADER: Grader = 'PSA';

// ─── Card Identity Types ───

export interface ResolvedCard {
  id: string;
  name: string;
  setName: string;
  setCode: string;
  number: string;
  year: number;
  rarity?: string;
  variant?: string; // "1st Edition", "Shadowless", "Holo", etc.
  imageUrl?: string;
  confidence: number; // 0-1.0 from parse-title API
  sku?: string; // deterministic "{setCode}-{number}" e.g. "swsh7-215"
}

export interface CardCandidate {
  card: ResolvedCard;
  confidence: number;
  matchReason: string;
}

export interface ResolveResult {
  success: boolean;
  bestMatch?: ResolvedCard;
  candidates: CardCandidate[];
  originalQuery: string;
  needsDisambiguation: boolean; // true when confidence in disambiguate range
  disambiguationReason?: string; // human-readable explanation
}

// ─── Pricing Types ───

export interface PricePoint {
  source: string;
  price: number;
  currency: string;
  date: string;
  saleType?: 'completed' | 'active' | 'estimate';
}

export interface FairMarketValue {
  cardId: string;
  grade: number;
  grader: Grader;
  fmv: number;
  currency: string;
  prices: PricePoint[];
  lastUpdated: string;
  populationCount?: number;
  pricingSource?: string; // e.g. "PriceCharting PSA 10" or "PriceCharting PSA 10 (approximate for BGS 10)"
}

// ─── eBay Scanner Types ───

export type ListingType = 'BuyItNow' | 'Auction' | 'BestOffer';

export interface EbayListing {
  itemId: string;
  title: string;
  price: number;
  currency: string;
  shippingCost: number;
  totalPrice: number; // price + shipping
  listingType: ListingType;
  sellerUsername: string;
  sellerFeedbackScore: number;
  sellerFeedbackPercent: number;
  imageUrl?: string;
  itemUrl: string;
  endDate?: string;
  condition?: string;
  bidCount?: number;
}

export interface ScanResult {
  card: ResolvedCard;
  listings: EbayListing[];
  scannedAt: string;
  totalFound: number;
  error?: string;
}

// ─── eBay Search Override Types ───

export interface EbaySearchOverride {
  cardId: string;
  customQuery?: string;          // Replace auto-generated query entirely
  requiredKeywords?: string[];   // Listing title MUST contain all (post-filter)
  excludeKeywords?: string[];    // Listing title MUST NOT contain any (post-filter)
  notes: string;                 // Why this override exists
  createdAt: string;
  autoGenerated?: boolean;       // true = created by report analysis, not manual
  reportCount?: number;          // How many reports contributed to this override
}

// ─── Deal Scorer Types ───

export type DealSignal =
  | 'strong_buy'
  | 'buy'
  | 'fair'
  | 'overpriced'
  | 'avoid';

export interface ScoredDeal {
  listing: EbayListing;
  card: ResolvedCard;
  fmv: FairMarketValue;
  score: number; // 0-100
  signal: DealSignal;
  reasoning: string;
  savingsPercent: number;
  savingsAmount: number;
}

// ─── Storage Adapter ───

export interface StorageAdapter {
  get<T>(key: string): Promise<T | null>;
  set<T>(key: string, value: T): Promise<void>;
  delete(key: string): Promise<boolean>;
  list(prefix: string): Promise<string[]>;
}

// ─── Legacy Agent Types (used by telegram, logging, feedback modules) ───

export interface Agent {
  id: string; // UUID
  name: string;
  description: string;
  apiKey: string; // gacha_ prefixed
  createdAt: string; // ISO 8601
  lastSeenAt?: string;
}

export interface AgentHeartbeatState {
  agentId: string;
  lastSkillUpdate?: string;
  lastScan?: string;
  lastPrune?: string;
  activeAlerts: number;
  errorCount: number;
  lastPing?: string;
}

export type InteractionType = 'resolve' | 'price' | 'scan' | 'find' | 'feedback' | 'disambiguate';

export interface InteractionLog {
  id: string;
  agentId: string;
  type: InteractionType;
  input: unknown;
  output: unknown;
  timestamp: string;
}

export interface DisambiguationSession {
  id: string;
  agentId: string;
  query: string;
  candidates: CardCandidate[];
  selectedIndex?: number;
  selectedCard?: ResolvedCard;
  status: 'pending' | 'selected' | 'expired';
  createdAt: string;
  resolvedAt?: string;
  chatId?: string;
}

export interface FeedbackEntry {
  id: string;
  interactionId: string | null;
  agentId: string;
  feedbackText: string;
  timestamp: string;
  telegramContext?: {
    chatId: string | number;
    userId?: string | number;
    username?: string;
    replyToText?: string;
  };
}

// ─── Inventory Types ───

export interface InventoryItem {
  id: string;
  name: string;
  setName: string;
  number: string;
  grade: number;
  grader: Grader;
  price: number;          // Gacha's asking price in USD
  quantity: number;
  imageUrl?: string;
  variant?: string;
  certNumber?: string;
  populationCount?: number; // PSA population at this grade
  year?: number;            // Card year
  sku?: string;             // deterministic "{setCode}-{number}" e.g. "swsh7-215"
  status: 'available' | 'reserved' | 'sold';
  createdAt: string;
}

// ─── Chat Agent Types ───

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

// ─── Popular Cards / Watchlist Types ───

export interface PopularCardSeed extends ResolvedCard {
  defaultGrade: number;
  tags?: string[];
}

export interface RecentSearchEntry {
  card: ResolvedCard;
  query: string;
  timestamp: string; // ISO date
}

export interface WatchlistEntry {
  id: string;
  email: string;
  cardId: string;
  grade: number;
  grader: Grader;
  cardName: string;
  setName: string;
  imageUrl?: string;
  createdAt: string;
}

export interface ListingReport {
  id: string;
  ebayItemId: string;
  ebayTitle: string;
  ebayUrl: string;
  cardId: string;
  cardName: string;
  grade: number;
  reportedSignal: DealSignal;
  reportedScore: number;
  reportedFmv: number | null;
  reportedPrice: number;
  reason?: string;
  timestamp: string;
}

export interface PricingReport {
  id: string;
  cardId: string;
  cardName: string;
  setName?: string;
  grade: number;
  message: string;
  email?: string;
  timestamp: string;
}

export interface AgentResponse {
  text: string;
  cards?: ResolvedCard[];
  deals?: ScoredDeal[];
  inventory?: InventoryItem[];
  fmv?: FairMarketValue;
  disambiguation?: CardCandidate[];
}

// ─── Multi-Source Pricing Types ───

export interface PptEbayGradeData {
  fmv: number;
  confidence: 'high' | 'medium' | 'low';
  salesCount: number;
  medianPrice: number | null;
  marketTrend: 'up' | 'down' | null;
}

export interface PptEbayPricing {
  label: string;
  gradeData: Record<number, PptEbayGradeData>;
}

export interface TcgPlayerPricing {
  label: string;
  market: number | null;
  low: number | null;
  mid: number | null;
  high: number | null;
  variant: string;
}

export interface PriceChartingPricing {
  label: string;
  fmv: number | null;
  allGrades: Record<number, number | null>;
}

export interface MultiSourcePricing {
  card: ResolvedCard;
  grade: number;
  grader: Grader;
  fmv: number | null;
  allGrades: Record<number, number | null>;
  sources: {
    priceCharting: PriceChartingPricing | null;
    pptEbay: PptEbayPricing | null;
    tcgPlayer: TcgPlayerPricing | null;
  };
}

// ─── Config ───

export interface GachaAgentConfig {
  pokemonPriceTracker: {
    apiKey: string;
    baseUrl: string;
  };
  priceCharting?: {
    apiKey: string;
  };
  pokemonTcg?: {
    apiKey: string;
  };
  ebay?: {
    appId: string;
    certId: string;
    devId?: string;
    sandbox?: boolean;
    whitelistSellers?: string[];
  };
  telegram?: {
    botToken: string;
    defaultChatId?: string;
  };
  developer?: {
    chatId: string;
  };
  gemini?: {
    apiKey: string;
  };
  storage: {
    type: 'json' | 'supabase';
    jsonPath?: string;
    supabaseUrl?: string;
    supabaseKey?: string;
  };
}
