import type { StorageAdapter, EbaySearchOverride, EbayListing, ResolvedCard, ListingReport } from '../types/index.js';
import { inferVariantKeywords } from './ebay.js';

const KEY_PREFIX = 'ebay-override:';
const REPORT_KEY_PREFIX = 'listing-report:';

export class EbayOverrideRegistry {
  constructor(private storage: StorageAdapter) {}

  // ─── Report Storage ───

  async storeReport(report: ListingReport): Promise<void> {
    const key = `${REPORT_KEY_PREFIX}${report.cardId}`;
    const existing = (await this.storage.get<ListingReport[]>(key)) ?? [];
    existing.push(report);
    await this.storage.set(key, existing);
  }

  async getReports(cardId: string): Promise<ListingReport[]> {
    return (await this.storage.get<ListingReport[]>(`${REPORT_KEY_PREFIX}${cardId}`)) ?? [];
  }

  // ─── Report-Driven Auto-Override ───

  async suggestFromReport(
    card: ResolvedCard,
    report: ListingReport,
  ): Promise<EbaySearchOverride | null> {
    const variantKeywords = inferVariantKeywords(card);
    if (variantKeywords.length === 0) return null;

    // Check if the reported title lacks expected variant keywords
    const titleLower = report.ebayTitle.toLowerCase();
    const missing = variantKeywords.filter((kw) => !titleLower.includes(kw.toLowerCase()));
    if (missing.length === 0) return null;

    // Don't overwrite manual overrides
    const existing = await this.get(card.id);
    if (existing && !existing.autoGenerated) return null;

    // Create or update auto-override
    const reportCount = (existing?.reportCount ?? 0) + 1;
    const mergedRequired = existing?.requiredKeywords ?? [];
    for (const kw of variantKeywords) {
      if (!mergedRequired.some((r) => r.toLowerCase() === kw.toLowerCase())) {
        mergedRequired.push(kw);
      }
    }

    const override = await this.set({
      cardId: card.id,
      requiredKeywords: mergedRequired,
      excludeKeywords: existing?.excludeKeywords,
      notes: `Auto-generated from ${reportCount} report(s): listing titles missing variant keywords [${missing.join(', ')}]`,
      autoGenerated: true,
      reportCount,
    });
    return override;
  }

  async set(override: Omit<EbaySearchOverride, 'createdAt'>): Promise<EbaySearchOverride> {
    const entry: EbaySearchOverride = {
      ...override,
      createdAt: new Date().toISOString(),
    };
    await this.storage.set(`${KEY_PREFIX}${override.cardId}`, entry);
    return entry;
  }

  async get(cardId: string): Promise<EbaySearchOverride | null> {
    return this.storage.get<EbaySearchOverride>(`${KEY_PREFIX}${cardId}`);
  }

  async getAll(): Promise<EbaySearchOverride[]> {
    const keys = await this.storage.list(KEY_PREFIX);
    const results: EbaySearchOverride[] = [];
    for (const key of keys) {
      const entry = await this.storage.get<EbaySearchOverride>(key);
      if (entry) results.push(entry);
    }
    return results;
  }

  async delete(cardId: string): Promise<boolean> {
    return this.storage.delete(`${KEY_PREFIX}${cardId}`);
  }

  static applyTitleFilter(listings: EbayListing[], override: EbaySearchOverride): EbayListing[] {
    const required = override.requiredKeywords?.map((kw) => kw.toLowerCase()) ?? [];
    const excluded = override.excludeKeywords?.map((kw) => kw.toLowerCase()) ?? [];

    if (required.length === 0 && excluded.length === 0) return listings;

    return listings.filter((listing) => {
      const title = listing.title.toLowerCase();
      if (required.length > 0 && !required.every((kw) => title.includes(kw))) return false;
      if (excluded.length > 0 && excluded.some((kw) => title.includes(kw))) return false;
      return true;
    });
  }
}
